name: Release
on:
  push:
    branches: [ master, staging ]

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      # Create a dist/ directory that contains everything from the 
      - run: |
          cp -r . /tmp/dist/
          cp -r /tmp/dist dist/

      # Replace the first occurrence of 'yjson' with '@joebobmiles/yjson' in
      # package.json. This allows us to insert 'yjson' in places other than the
      # package name without fearing that they will be edited.
      - run: sed -i "0,/yjson/{s//@joebobmiles\/yjson/}" dist/package.json

      - run: npm ci
      
      - run: npx semantic-release --debug
        env:
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: ${{ secrets.NPM_CONFIG_REGISTRY }}
          SCOPED_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SCOPED_NPM_CONFIG_REGISTRY: ${{ secrets.NPM_CONFIG_REGISTRY }}
          GITHUB_NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_NPM_CONFIG_REGISTRY: ${{ secrets.GH_NPM_CONFIG_REGISTRY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
