name: Verify
on: 
  push:
    branches-ignore: [ master ]
  pull_request:
    branches-ignore: [ master ]

jobs:
  commitlint:
    name: Verify commit history
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npx commitlint --from HEAD~1 --to HEAD --verbose

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npm test